[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = ".next/serverless"
  node_bundler = "esbuild"

[functions."api/*"]
  included_files = ["prisma/**/*"]

# Ensure Prisma is available during build
[build.processing]
  skip_processing = false

# Add build plugins if needed
[[plugins]]
  package = "@netlify/plugin-nextjs"
